wandb_version: 1

_n_gpu:
  desc: null
  value: 0
_name_or_path:
  desc: null
  value: distilgpt2
_num_labels:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    python_version: 3.8.5
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      4: 3.8.5
      5: 0.10.31
      6: 4.6.1
      8:
      - 3
      - 5
activation_function:
  desc: null
  value: gelu_new
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - GPT2LMHeadModel
attn_pdrop:
  desc: null
  value: 0.1
bad_words_ids:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: 50257
chunk_size_feed_forward:
  desc: null
  value: 0
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
embd_pdrop:
  desc: null
  value: 0.1
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 50258
eval_accumulation_steps:
  desc: null
  value: 1
eval_batch_size:
  desc: null
  value: 64
eval_steps:
  desc: null
  value: 500
evaluation_strategy:
  desc: null
  value: epoch
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
id2label:
  desc: null
  value:
    '0': LABEL_0
ignore_data_skip:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_epsilon:
  desc: null
  value: 1.0e-05
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: true
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: runs\Jun14_14-13-03_DESKTOP-LFJENP8
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: loss
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: gpt2
mp_parameters:
  desc: null
  value: ''
n_ctx:
  desc: null
  value: 1024
n_embd:
  desc: null
  value: 768
n_head:
  desc: null
  value: 12
n_inner:
  desc: null
  value: null
n_layer:
  desc: null
  value: 6
n_positions:
  desc: null
  value: 1024
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 5
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: Data\model\model1/
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: true
pad_token_id:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 64
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
prediction_loss_only:
  desc: null
  value: true
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
resid_pdrop:
  desc: null
  value: 0.1
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: Data\model\model1/
save_steps:
  desc: null
  value: -1
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: None
scale_attn_weights:
  desc: null
  value: true
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: false
summary_activation:
  desc: null
  value: null
summary_first_dropout:
  desc: null
  value: 0.1
summary_proj_to_labels:
  desc: null
  value: true
summary_type:
  desc: null
  value: cls_index
summary_use_proj:
  desc: null
  value: true
task_specific_params:
  desc: null
  value:
    text-generation:
      do_sample: true
      max_length: 50
temperature:
  desc: null
  value: 1.0
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 16
transformers_version:
  desc: null
  value: 4.6.1
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 50259
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
